kernel:
  image: "linuxkit/kernel:4.9.x"
  cmdline: "console=ttyS0 console=tty0 page_poison=1"
init:
  - linuxkit/init:1b8a7e394d2ec2f1fdb4d67645829d1b5bdca037
  - linuxkit/runc:3a4e6cbf15470f62501b019b55e1caac5ee7689f
  - linuxkit/containerd:be69ded7ed4437e2989da850581b631bac877d3e
  - linuxkit/ca-certificates:75cf419fb58770884c3464eb687ec8dfc704169d
onboot:
  - name: sysctl
    image: "linuxkit/sysctl:3aa6bc663c2849ef239be7d941d3eaf3e6fcc018"
  - name: format
    image: "linuxkit/format:180cb2dc1de5e60373385080f8148abf10a3afac"
  - name: mount
    image: "linuxkit/mount:ff5338822f20375b8913f5a80f9ed4f6ea9a592b"
    command: ["/mount.sh", "/var/lib/etcd"]
  - name: dhcpcd
    image: "linuxkit/dhcpcd:7d2b8aaaf20c24ad7d11a5ea2ea5b4a80dc966f1"
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
  - name: metadata
    image: "linuxkit/metadata:4e73345cdcb4f7e9df07b0ee7aede652960297f2"
services:
  - name: rngd
    image: "linuxkit/rngd:1fa4de44c961bb5075647181891a3e7e7ba51c31"
  - name: ntpd
    image: "linuxkit/openntpd:45deeb05f736162d941c9bf494983f655ab80aa5"
  - name: node_exporter
    image: "linuxkit/node_exporter:265b35e1c9bd659fff22b0345fc7c8735c787b3c"
  - name: etcd
    image: "moby/etcd"
    capabilities:
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE
     - CAP_SYS_ADMIN
     - CAP_MKNOD
    net: host
    binds:
     - /var/lib/etcd:/var/lib/etcd
     - /var/config/etcd:/etc/etcd
trust:
  org:
    - linuxkit
